Repository deco-sites/std, pull requests merged in 2023-05, with the labels that each got.

#61 Add cookies when fetching products from proxy cache
  packs/vtex/loaders/legacy/productDetailsPage.ts
  packs/vtex/loaders/legacy/productList.ts
  packs/vtex/loaders/legacy/productListingPage.ts
  packs/vtex/loaders/legacy/relatedProductsLoader.ts
Labels: bug

#62 fix: ProductGroupURL
  commerce/sdk/sendAnalyticsEvent.ts
  import_map.json
  packs/vtex/utils/transform.ts
  schemas.gen.json
Labels: enhancement, breaking-change

#63 feat: Allow passing productGroupID on RelatedProducts
  functions/vtexLegacyRelatedProductsLoader.ts
  import_map.json
  packs/vtex/loaders/legacy/relatedProductsLoader.ts
  schemas.gen.json
Labels: enhancement

#65 Adds a simple retry when server closes the connection before the message is transmitted
  utils/fetch.test.ts
  utils/fetch.ts
Labels: enhancement

#66 feat: remove productgroup from product variations
  packs/vtex/utils/transform.ts
Labels: enhancement

#67 feat: add loading state to autocomplete hook
  packs/vtex/hooks/useAutocomplete.ts
Labels: enhancement

#69 Add target on cockatiel import, remove pageOffset default, and use sort prop on listing page.
  live.gen.ts
  packs/vtex/loaders/intelligentSearch/productListingPage.ts
  packs/vtex/loaders/legacy/productListingPage.ts
  schemas.gen.json
  utils/fetch.ts
Labels: bug

#82 feat: Work with legacy params on IS
  packs/vtex/loaders/intelligentSearch/productListingPage.ts
  packs/vtex/utils/transform.ts
Labels: enhancement

#91 auto resolve tailwind to the default tailwind config
  tailwindv3.ts
Labels: enhancement

#92 hotfix: correctly resolve tailwind.config.ts
  schemas.gen.json
  tailwindv3.ts
Labels: bug

#99 fix: remove duplicate tags
  components/seo/Metatags.tsx
Labels: ignore-for-release

#100 feat: Improve page type and parameters detection
  components/VTEXPortalDataLayerCompatibility.tsx
Labels: enhancement

#103 fix: trigger vtex compatibility event with dataLayer.push
  components/VTEXPortalDataLayerCompatibility.tsx
Labels: bug
