Repository deco-sites/std, pull requests merged in 2023-08, with the labels that each got.

#172 feat: font loader
  import_map.json
  live.gen.ts
  loaders/x/font.ts
  packs/font/loaders/font.ts
  packs/font/loaders/googleFonts.ts
  packs/font/types.ts
  schemas.gen.json
  utils/withFontServer.ts
Labels: enhancement

#173 chore: font loader allow origin list
  packs/font/loaders/font.ts
Labels: bug

#180 feat: add similars
  doccache.zst
  packs/vtex/loaders/intelligentSearch/productDetailsPage.ts
  packs/vtex/loaders/intelligentSearch/productList.ts
  packs/vtex/loaders/intelligentSearch/productListingPage.ts
  packs/vtex/loaders/intelligentSearch/suggestions.ts
  packs/vtex/loaders/legacy/productDetailsPage.ts
  packs/vtex/loaders/legacy/productList.ts
  packs/vtex/loaders/legacy/productListingPage.ts
  packs/vtex/utils/similars.ts
Labels: enhancement

#184 feat: add Brand to Product
  commerce/nuvemShop/transform.ts
  commerce/shopify/transform.ts
  commerce/types.ts
  packs/linxImpulse/utils/transform.ts
  packs/vtex/types.ts
  packs/vtex/utils/transform.ts
Labels: enhancement, breaking-change
